### ISSUE TITLE
Document input values and units

### ISSUE THREAD

**Issue by slhck** [stootaghaj/ITU-G1072#3]
In the example in the README it says:

> Here you can find an example for a condition with 1 Mbps, 60 fps, packet loss of 5%, delay of 25 ms, Interaction complexity of "High", and Video Complexity of "Low" level:

Then this code is shown:

```
    python G1072.py --bitrate=2  --framerate=60  
                    --packetloss=0 --packetlossUDP=0 
                    --delay=200 --coding_res=1920x1080  
                    --Icomplexity=High --Vcomplexity=High  
                    --test_type=parameters
```

This seems inconsistent. The bitrate in the code is not 1 Mbps, and the delay is given as 200. There is no packet loss and the vido complexity is set to high instead of low as described above.

Please harmonize the description and the example, and document the units for the parameters.

**Comment by stootaghaj** [comment]
Done!

**Comment by slhck** [comment]
Thank you!
